<script lang="ts" setup>
	const store = useRoomStore()
	const model = useRoom()
	const user = useUser()
	const userStore = useUserStore()
	const imageFiles = ref<File[]>([])
	const autoGenerateDescription = ref(false)
	onMounted(() => {
		if (!store.form.id && useRoute().params.id != "add") {
			model.fetchDetail()
		}
		if (useRoute().params.id === "add") {
			store.form.beds = [
				{
					number: "",
					type: "Single",
					room_id: undefined,
					capacity: 1,
					max_capacity: 2,
				},
			]
		}
		store.form.deleted_image_ids = []
	})
	userStore.pagination.exclude_clients = true
	user.fetchData()
	onBeforeUnmount(() => {
		userStore.pagination.exclude_clients = false
	})
	function generateDescription(): void {
		if (!autoGenerateDescription.value) return
		nextTick(() => {
			const form = store.form as RoomForm

			const segments: string[] = []

			segments.push(form.is_ac ? "AC" : "Non AC")

			const beds = form.beds || []
			const totalCapacity = beds.reduce(
				(sum, bed) => sum + (Number(bed.capacity) || 0),
				0,
			)

			const types: ("Single" | "Double" | "Twin")[] = [
				"Single",
				"Double",
				"Twin",
			]

			types.forEach((type) => {
				const count = beds.filter((bed) => bed.type === type).length
				if (count > 0) {
					const plural = count > 1 ? "s" : ""
					segments.push(`${count} ${type.toLowerCase()} bed${plural}`)
				}
			})

			let finalDescription = segments.join(", ")
			finalDescription += `, accommodates ${totalCapacity}.`

			store.form.description = finalDescription
		})
	}
</script>
<template>
	<div class="flex flex-col items-center">
		<u-card style="min-width: min(400px, 90vw)" class="">
			<u-form
				:schema="roomFormSchema()"
				:state="store.form"
				@submit="model.submitForm(imageFiles)"
				class="space-y-4 w-full"
			>
				<u-form-field label="Room no" name="number">
					<u-input
						v-model="store.form.number"
						icon="i-lucide-user"
						type="text"
					/>
				</u-form-field>
				<u-form-field label="Rate" name="rate">
					<u-input
						v-model="store.form.rate"
						icon="i-lucide-indian-rupee"
						type="number"
						step="0.01"
					/>
				</u-form-field>
				<div class="grid grid-cols-2 gap-2">
					<u-form-field name="is_ac">
						<u-checkbox
							@update:model-value="generateDescription"
							variant="card"
							v-model="store.form.is_ac"
							label="AC"
						/>
					</u-form-field>
					<u-form-field name="is_dormatory">
						<u-checkbox
							@update:model-value="generateDescription"
							variant="card"
							v-model="store.form.is_dormatory"
							label="Dorm"
						/>
					</u-form-field>
				</div>
				<u-form-field label="Description" name="description">
					<div class="flex space-x-1.5 items-center">
						<div class="flex-1">
							<u-textarea
								v-model="store.form.description"
								icon="i-lucide-notepad-text"
							>
							</u-textarea>
						</div>
						<div
							@click="
								() => {
									autoGenerateDescription = !autoGenerateDescription
									generateDescription()
								}
							"
							class="cursor-default flex flex-col items-center"
						>
							<USwitch
								class="pointer-events-none"
								v-model="autoGenerateDescription"
							/>
							<div class="mb-2">Generate</div>
						</div>
					</div>
				</u-form-field>
				<u-form-field label="Staff" name="staff_id">
					<USelectMenu
						class="w-full"
						v-model="store.form.staff_id"
						value-key="id"
						label-key="name"
						:items="userStore.data.data"
					/>
				</u-form-field>

				<u-form-field label="Image" name="images">
					<UFileUpload
						class="w-full"
						accept="image/jpeg,image/png"
						v-model="imageFiles"
						multiple
					></UFileUpload>
				</u-form-field>
				<div class="grid grid-cols-3 gap-2 px-4">
					<template v-for="(image, index) in store.form.images">
						<div class="bg-elevated relative">
							<UButton
								@click="
									() => {
										if (!store.form.deleted_image_ids) {
											store.form.deleted_image_ids = []
										}
										store.form.deleted_image_ids.push(image.id)
										store.form.images.splice(index, 1)
									}
								"
								variant="outline"
								color="neutral"
								class="bg-white rounded-full absolute top-0 right-0 text-black hover:bg-white"
								style="padding: 2px"
							>
								<UIcon size="14" name="i-lucide-x" />
							</UButton>

							<NuxtImg
								:src="image.url"
								style="aspect-ratio: 1; object-fit: cover"
							/>
						</div>
					</template>
				</div>
				<div class="grid grid-cols-2 border border-default gap-2 p-2">
					<h4 class="col-span-2 mb-2">Beds</h4>
					<template v-for="(bed, index) in store.form.beds" :key="index">
						<div class="col-span-2" v-if="index != 0">
							<USeparator />
							<div class="text-right pt-1">
								<u-button
									size="xs"
									class="rounded-full"
									variant="outline"
									color="neutral"
									@click="
										() => {
											store.form.beds.splice(index, 1)
											if (!bed.id) return
											if (!store.form.deleted_bed_ids) {
												store.form.deleted_bed_ids = [bed.id]
											} else {
												store.form.deleted_bed_ids?.push(bed.id)
											}
										}
									"
									icon="i-lucide-x"
								>
								</u-button>
							</div>
						</div>
						<UFormField :name="`beds.${index}.number`">
							<UInput
								@update:model-value="generateDescription"
								v-model="bed.number"
								placeholder=""
								:ui="{
									base: 'peer',
								}"
							>
								<label
									class="pointer-events-none absolute left-0 -top-2.5 text-highlighted text-xs font-medium px-1.5 transition-all peer-focus:-top-2.5 peer-focus:text-highlighted peer-focus:text-xs peer-focus:font-medium peer-placeholder-shown:text-sm peer-placeholder-shown:text-dimmed peer-placeholder-shown:top-1.5 peer-placeholder-shown:font-normal"
								>
									<span class="inline-flex bg-default px-1">Name/number</span>
								</label>
							</UInput>
						</UFormField>

						<UFormField :name="`beds.${index}.type`">
							<UInputMenu
								@update:model-value="generateDescription"
								clear
								open-on-focus
								v-model="bed.type"
								placeholder=""
								:items="['Single', 'Twin', 'Double']"
							>
							</UInputMenu>
						</UFormField>
						<UFormField :name="`beds.${index}.capacity`">
							<UInputMenu
								@update:model-value="generateDescription"
								clear
								v-model="bed.capacity"
								placeholder=""
								:ui="{
									base: 'peer',
								}"
								:items="[1, 2]"
								type="number"
								hint="Capacity"
							>
							</UInputMenu>
						</UFormField>
						<UFormField :name="`beds.${index}.max_capacity`">
							<UInputMenu
								@update:model-value="generateDescription"
								clear
								v-model="bed.max_capacity"
								placeholder=""
								:ui="{
									base: 'peer',
								}"
								:items="[1, 2]"
								type="number"
							>
							</UInputMenu>
						</UFormField>
					</template>
					<div class="p-1 col-span-2 text-right">
						<u-button
							size="lg"
							variant="outline"
							color="neutral"
							class="h-full"
							@click="
								() => {
									store.form.beds.push({
										number: '',
										type: 'Single',
										room_id: undefined,
										capacity: 1,
										max_capacity: 2,
									})
								}
							"
						>
							Add Bed
						</u-button>
					</div>
				</div>
				<div class="flex justify-end space-x-2 sticky bottom-0">
					<u-button
						size="lg"
						variant="outline"
						color="neutral"
						class="h-full"
						:disabled="store.loadingSubmitRoomForm"
						@click="
							() => {
								if (useRoute().name == 'hotels-rooms-id-form') {
									useRouter().push({
										name: 'hotels-rooms',
									})
								}
								useInvoiceStore().showInvoiceFormModal = false
							}
						"
					>
						Cancel
					</u-button>
					<u-button
						size="lg"
						:loading="store.loadingSubmitRoomForm"
						class=""
						type="submit"
					>
						Submit
					</u-button>
				</div>
			</u-form>
		</u-card>
	</div>
</template>

<style scoped>
	.relative.inline-flex.items-center {
		width: 100%;
	}
</style>
